version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: vikahotel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sapassword
      POSTGRES_DB: vikahotel
    ports:
      - "5432:5432"
    volumes:
      - vikahotel_pg_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7-alpine
    container_name: vikahotel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - vikahotel_redis_data:/data

  # qdrant:
  #   image: qdrant/qdrant:v1.12.4
  #   container_name: vikahotel-qdrant
  #   restart: unless-stopped
  #   ports:
  #     - "6333:6333"   # REST API + giao diện web: http://localhost:6333/dashboard
  #   volumes:
  #     - vikahotel_qdrant_data:/qdrant/storage

volumes:
  vikahotel_pg_data:
  vikahotel_redis_data:
  # vikahotel_qdrant_data:
